### ISSUE TITLE
Express server crashes when seneca plugin returns an error

### ISSUE THREAD

**Issue by djensen47** [senecajs/seneca-web-adapter-express#8]
1. Checkout the senecajs/seneca-web repo: 
2. Edit the file `docs/examples/common/plugin.js`
Change this
```
  seneca.add('role:todo,cmd:list', (msg, done) => {
    done(null, {ok: true})
  })
```
to this
```
  seneca.add('role:todo,cmd:list', (msg, done) => {
    done(new Error('No todo lists found'), {ok: false})
  })
```

3. Run the server `node docs/examples/using-express.js`
4. Open your browser to http://localhost:4000/todo/list

The result is a FATAL error:
```
Seneca Fatal Error
==================

Message: seneca: Action cmd:list,role:todo failed: .

Code: act_execute

Details: { message: '',
  pattern: 'cmd:list,role:todo',
  fn: [Function],
  cb: [Function],
  instance: 'Seneca/mvacw49oa56r/1478047256740/51658/3.2.1/-',
  'orig$':
   Error
       at Seneca.seneca.add (/open-source/seneca-web/docs/examples/common/plugin.js:7:10)
       at execute_action (/open-source/seneca-web/node_modules/seneca/seneca.js:1015:20)
       at Object.act_fn [as fn] (/open-source/seneca-web/node_modules/seneca/seneca.js:911:11)
       at Immediate.processor (/open-source/seneca-web/node_modules/gate-executor/gate-executor.js:131:14)
       at runCallback (timers.js:637:20)
       at tryOnImmediate (timers.js:610:5)
       at processImmediate [as _immediateCallback] (timers.js:582:5),
  'message$': '',
  plugin: {} }

Stack:
    at Seneca.seneca.add (/open-source/seneca-web/docs/examples/common/plugin.js:7:10)
    at execute_action (/open-source/seneca-web/node_modules/seneca/seneca.js:1015:20)
    at Object.act_fn [as fn] (/open-source/seneca-web/node_modules/seneca/seneca.js:911:11)
    at Immediate.processor (/open-source/seneca-web/node_modules/gate-executor/gate-executor.js:131:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

Instance: Seneca/mvacw49oa56r/1478047256740/51658/3.2.1/-
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at Seneca.act_done (/open-source/seneca-web/node_modules/seneca/seneca.js:1054:29)

When: 2016-11-02T00:41:02.825Z

Log: {kind:null,plugin:seneca,tag:3.2.1,id:mvacw49oa56r/1478047256740/51658/3.2.1/-,code:act_execute,notice:seneca:

Node:
  { http_parser: '2.7.0', node: '6.9.1', v8: '5.1.281.84', uv: '1.9.1', zlib: '1.2.8', ares: '1.10.1-DEV', icu: '57.1', modules: '48', openssl: '1.0.2j' },
  { debug: false, uv: true, ipv6: true, tls_npn: true, tls_alpn: true, tls_sni: true, tls_ocsp: true, tls: true },
  [ 'Binding contextify', 'Binding natives', 'NativeModule events', 'NativeModule util', 'Binding uv', 'NativeModule buffer', 'Binding buffer', 'Binding util', 'NativeModule internal/util', 'NativeModule timers', 'Binding timer_wrap', 'NativeModule internal/linkedlist', 'NativeModule assert', 'NativeModule internal/process', 'Binding config', 'NativeModule internal/process/warning', 'NativeModule internal/process/next_tick', 'NativeModule internal/process/promises', 'NativeModule internal/process/stdio', 'Binding constants', 'NativeModule path', 'NativeModule module', 'NativeModule internal/module', 'NativeModule vm', 'NativeModule fs', 'Binding fs', 'NativeModule stream', 'NativeModule _stream_readable', 'NativeModule internal/streams/BufferList', 'NativeModule _stream_writable', 'NativeModule _stream_duplex', 'NativeModule _stream_transform', 'NativeModule _stream_passthrough', 'Binding fs_event_wrap', 'NativeModule tty', 'NativeModule net', 'NativeModule internal/net', 'Binding cares_wrap', 'Binding tty_wrap', 'Binding tcp_wrap', 'Binding pipe_wrap', 'Binding stream_wrap', 'Binding signal_wrap', 'NativeModule http', 'NativeModule _http_incoming', 'NativeModule _http_common', 'Binding http_parser', 'NativeModule internal/freelist', 'NativeModule _http_outgoing', 'NativeModule _http_server', 'NativeModule _http_agent', 'NativeModule _http_client', 'NativeModule url', 'Binding icu', 'NativeModule querystring', 'NativeModule crypto', 'Binding crypto', 'NativeModule internal/streams/lazy_transform', 'NativeModule string_decoder', 'NativeModule console', 'NativeModule os', 'Binding os', 'NativeModule https', 'NativeModule tls', 'NativeModule _tls_common', 'NativeModule _tls_wrap', 'NativeModule _stream_wrap', 'Binding js_stream', 'Binding tls_wrap', 'NativeModule _tls_legacy', 'NativeModule cluster', 'NativeModule dgram', 'Binding udp_wrap', 'NativeModule child_process', 'Binding spawn_sync', 'NativeModule internal/child_process', 'Binding process_wrap', 'NativeModule internal/socket_list', 'NativeModule internal/cluster' ]

Process:
  pid=51658, arch=x64, platform=darwin,
  path=/Users/djensen/.nvm/versions/node/v6.9.1/bin/node,
  argv=[ '/Users/djensen/.nvm/versions/node/v6.9.1/bin/node',  '/open-source/seneca-web/docs/examples/using-express.js' ],
  env={ MANPATH: '/Users/djensen/.nvm/versions/node/v6.9.1/share/man:/usr/local/git/share/man:/usr/local/share/man:/usr/share/man:/opt/X11/share/man:/Library/Developer/CommandLineTools/usr/share/man',  TERM_PROGRAM: 'iTerm.app',  NVM_CD_FLAGS: '-q',  TERM: 'xterm-256color',  SHELL: '/bin/zsh',  TMPDIR: '/var/folders/3g/75g3h8cj68z3ms77nqlnr3m80000gn/T/',  NVM_PATH: '/Users/djensen/.nvm/versions/node/v6.9.1/lib/node',  Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.XF53bIWSkI/Render',  TERM_PROGRAM_VERSION: '2.9.20160430-nightly',  TERM_SESSION_ID: 'w0t0p3:35920AB5-A1B7-4FBC-A797-34029A46ABE4',  ZSH: '/Users/djensen/.oh-my-zsh',  NVM_DIR: '/Users/djensen/.nvm',  USER: 'djensen',  SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.dpqCJG7BSL/Listeners',  __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0',  PAGER: 'less',  LSCOLORS: 'exfxcxdxbxegedabagacad',  PATH: '/Users/djensen/.nvm/versions/node/v6.9.1/bin:/Users/djensen/bin:/usr/local/git/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/djensen/Library/Android/sdk/platform-tools',  _: '/Users/djensen/.nvm/versions/node/v6.9.1/bin/node',  NVM_NODEJS_ORG_MIRROR: 'https://nodejs.org/dist',  PWD: '/open-source/seneca-web',  LANG: 'en_US.UTF-8',  ITERM_PROFILE: 'Default',  XPC_FLAGS: '0x0',  XPC_SERVICE_NAME: '0',  SHLVL: '2',  HOME: '/Users/djensen',  COLORFGBG: '7;0',  ITERM_SESSION_ID: 'w0t0p3:35920AB5-A1B7-4FBC-A797-34029A46ABE4',  LESS: '-R',  LOGNAME: 'djensen',  LC_CTYPE: 'en_US.UTF-8',  NVM_BIN: '/Users/djensen/.nvm/versions/node/v6.9.1/bin',  NVM_IOJS_ORG_MIRROR: 'https://iojs.org/dist',  DISPLAY: '/private/tmp/com.apple.launchd.X4OT83Ktcd/org.macosforge.xquartz:0' }




SENECA TERMINATED at 2016-11-02T00:41:02.835Z. See above for error report.
```

To make sure I wasn't misunderstanding some basic concept I created a small standalone test:
```
var Seneca = require('seneca');
var seneca = Seneca();
seneca
  .use('./common/plugin')
  .ready( () => {
    seneca.act('role:todo,cmd:edit', {}, (err, reply) => console.log(err ? 'error' : 'no error'));
  });
```

This, as expected, prints out "error" it runs.

**Comment by tswaters** [comment]
In our seneca project at work, we routinely pass an error back as the first parameter to exit out of subsequent processing.... we've been setting `seneca.fixedargs.fatal$ = false` after initialization on everything to get around this and other fun with seneca error handling -- see https://github.com/senecajs/seneca/issues/398 for more discussion about errors in seneca.  Probably would have noticed this sooner if not for that.

--

Anyway, the key here is this line in that error stack, emphasis mine (also we should fix that hyperlink)

> ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, **or using a plugin seneca instance**, see senecajs.org/fatal.html)

If your reduced test was updated like so -- it would replicate what seneca-web is doing and crash as well:

```js
var Seneca = require('seneca');
var seneca = Seneca();
seneca
  .use('./common/plugin')
  .use(function () {
    // act using the plugin instance - this is what seneca-web adapters do
    this.add('role:test', (args, cb) => this.act('role:todo,cmd:list', args, cb))
  })
  .ready(() => {
    seneca.act('role:test', () => console.log('made it!')) // will not make it.
  });
```

To get around this, we could instead call from the root seneca instance - updating test case like this reports `made it!` (in addition to the error being logged normally)

```js
var Seneca = require('seneca');
var seneca = Seneca();
seneca
  .use('./common/plugin')
  .use(function () {
    // act upon the root seneca instance instead of plugin instance.
    this.add('role:test', (args, cb) => this.root.act('role:todo,cmd:list', args, cb))
  })
  .ready(() => {
    seneca.act('role:test', () => console.log('made it!'))
  });
```

@mcdonnelldean what are your thoughts on this?

Update this line https://github.com/senecajs/seneca-web-adapter-express/blob/master/seneca-web-adapter-express.js#L72 as follows:

```diff
-    seneca.act(route.pattern, payload, (err, response) => {
+    seneca.root.act(route.pattern, payload, (err, response) => {
```

**Comment by mcdonnelldean** [comment]
@tswaters Are there any reasons NOT to use root in your estimation?

**Comment by tswaters** [comment]
Oh shoot, totally didn't see that message.

I'm honestly not sure why there is a difference when plugins act on root vs. the seneca instance the plugin gets.... this touches on internals of seneca that I'm not to clear on, which is why I asked.
